Repository kubernetes-sigs/cluster-addons, pull requests merged in 2019-06, with the labels that each got.

#17 Adding contributors to OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#7 Example core-dns operator using declarative pattern
  coredns/.gitignore
  coredns/Makefile
  coredns/PROJECT
  coredns/README.md
  coredns/channels/packages/coredns/1.3.1/coredns.yaml.base
  coredns/channels/packages/coredns/1.3.1/manifest.yaml
  coredns/channels/stable
  coredns/cmd/manager/main.go
  coredns/config/crds/addons_v1alpha1_coredns.yaml
  coredns/config/default/kustomization.yaml
  coredns/config/default/manager_auth_proxy_patch.yaml
  coredns/config/default/manager_image_patch.yaml
  coredns/config/default/manager_prometheus_metrics_patch.yaml
  coredns/config/manager/manager.yaml
  coredns/config/rbac/auth_proxy_role.yaml
  coredns/config/rbac/auth_proxy_role_binding.yaml
  coredns/config/rbac/auth_proxy_service.yaml
  coredns/config/rbac/manager_role.yaml
  coredns/config/rbac/manager_role_binding.yaml
  coredns/config/samples/addons_v1alpha1_coredns.yaml
  coredns/go.mod
  coredns/go.sum
  coredns/hack/boilerplate.go.txt
  coredns/k8s/manager.yaml
  coredns/pkg/apis/addons/group.go
  coredns/pkg/apis/addons/v1alpha1/coredns_types.go
  coredns/pkg/apis/addons/v1alpha1/doc.go
  coredns/pkg/apis/addons/v1alpha1/register.go
  coredns/pkg/apis/addons/v1alpha1/zz_generated.deepcopy.go
  coredns/pkg/apis/addtoscheme_addons_v1alpha1.go
  coredns/pkg/apis/apis.go
  coredns/pkg/controller/add_coredns.go
  coredns/pkg/controller/controller.go
  coredns/pkg/controller/coredns/coredns_controller.go
  coredns/pkg/webhook/webhook.go
  coredns/tools.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#18 Add Patch to CoreDNS
  coredns/config/crds/addons_v1alpha1_coredns.yaml
  coredns/config/rbac/manager_role.yaml
  coredns/config/samples/addons_v1alpha1_coredns.yaml
  coredns/go.mod
  coredns/go.sum
  coredns/pkg/apis/addons/v1alpha1/coredns_types.go
  coredns/pkg/apis/addons/v1alpha1/zz_generated.deepcopy.go
  coredns/pkg/controller/coredns/coredns_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#20 coredns: Calculate ClusterIP for IPv4/IPv6 subnets with arbitrary offsets
  coredns/pkg/controller/coredns/coredns_controller.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S
