Repository kubernetes-sigs/cluster-addons, pull requests merged in 2020-06, with the labels that each got.

#60 Update dashboard operator golden tests
  dashboard/controllers/tests/patches-develop.out.yaml
  dashboard/controllers/tests/patches-stable.out.yaml
  dashboard/controllers/tests/simple-develop.out.yaml
  dashboard/controllers/tests/simple-stable.out.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#64 Fix minor nits in the CoreDNS operator
  coredns/channels/packages/coredns/1.6.9/kustomization.yaml
  coredns/config/manager/kustomization.yaml
  coredns/controllers/coredns_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#65 Add script for unit test
  hack/unit-test.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#66 Dashboard Operator: Use x-k8s.io instead of k8s.io
  dashboard/PROJECT
  dashboard/api/v1alpha1/groupversion_info.go
  dashboard/config/crd/bases/addons.x-k8s.io_dashboards.yaml
  dashboard/config/crd/kustomization.yaml
  dashboard/config/crd/patches/cainjection_in_dashboards.yaml
  dashboard/config/crd/patches/webhook_in_dashboards.yaml
  dashboard/config/rbac/dashboard_editor_role.yaml
  dashboard/config/rbac/dashboard_viewer_role.yaml
  dashboard/config/rbac/role.yaml
  dashboard/config/samples/addons_v1alpha1_dashboard.yaml
  dashboard/controllers/dashboard_controller.go
  dashboard/controllers/tests/patches-develop.in.yaml
  dashboard/controllers/tests/patches-develop.out.yaml
  dashboard/controllers/tests/patches-stable.in.yaml
  dashboard/controllers/tests/patches-stable.out.yaml
  dashboard/controllers/tests/simple-develop.in.yaml
  dashboard/controllers/tests/simple-develop.out.yaml
  dashboard/controllers/tests/simple-stable.in.yaml
  dashboard/controllers/tests/simple-stable.out.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#69 Flannel Operator
  flannel/.gitignore
  flannel/Dockerfile
  flannel/Makefile
  flannel/PROJECT
  flannel/api/v1alpha1/flannel_types.go
  flannel/api/v1alpha1/groupversion_info.go
  flannel/api/v1alpha1/zz_generated.deepcopy.go
  flannel/channels/latest
  flannel/channels/packages/flannel/0.10.0/manifest.yaml
  flannel/channels/packages/flannel/0.12.0/manifest.yaml
  flannel/channels/stable
  flannel/config/certmanager/certificate.yaml
  flannel/config/certmanager/kustomization.yaml
  flannel/config/certmanager/kustomizeconfig.yaml
  flannel/config/crd/bases/addons.x-k8s.io_flannels.yaml
  flannel/config/crd/kustomization.yaml
  flannel/config/crd/kustomizeconfig.yaml
  flannel/config/crd/patches/cainjection_in_flannels.yaml
  flannel/config/crd/patches/webhook_in_flannels.yaml
  flannel/config/default/kustomization.yaml
  flannel/config/default/manager_auth_proxy_patch.yaml
  flannel/config/default/manager_webhook_patch.yaml
  flannel/config/default/webhookcainjection_patch.yaml
  flannel/config/manager/kustomization.yaml
  flannel/config/manager/manager.yaml
  flannel/config/prometheus/kustomization.yaml
  flannel/config/prometheus/monitor.yaml
  flannel/config/rbac/auth_proxy_role.yaml
  flannel/config/rbac/auth_proxy_role_binding.yaml
  flannel/config/rbac/auth_proxy_service.yaml
  flannel/config/rbac/flannel_editor_role.yaml
  flannel/config/rbac/flannel_viewer_role.yaml
  flannel/config/rbac/kustomization.yaml
  flannel/config/rbac/leader_election_role.yaml
  flannel/config/rbac/leader_election_role_binding.yaml
  flannel/config/rbac/manager_role.yaml
  flannel/config/rbac/manager_role_binding.yaml
  flannel/config/rbac/role.yaml
  flannel/config/rbac/role_binding.yaml
  flannel/config/samples/addons_v1alpha1_flannel.yaml
  flannel/config/webhook/kustomization.yaml
  flannel/config/webhook/kustomizeconfig.yaml
  flannel/config/webhook/manifests.yaml
  flannel/config/webhook/service.yaml
  flannel/controllers/flannel_controller.go
  flannel/controllers/flannel_controller_test.go
  flannel/controllers/tests/latest.in.yaml
  flannel/controllers/tests/latest.out.yaml
  flannel/controllers/tests/patches-stable.in.yaml
  flannel/controllers/tests/patches-stable.out.yaml
  flannel/controllers/tests/simple-stable.in.yaml
  flannel/controllers/tests/simple-stable.out.yaml
  flannel/go.mod
  flannel/go.sum
  flannel/hack/boilerplate.go.txt
  flannel/main.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XXL

#68 Takes in manifest and generates role
  tools/rbac-gen/convert.go
  tools/rbac-gen/convert_test.go
  tools/rbac-gen/go.mod
  tools/rbac-gen/go.sum
  tools/rbac-gen/main.go
  tools/rbac-gen/manifest.yaml
  tools/rbac-gen/tests/clusterrole.in.yaml
  tools/rbac-gen/tests/clusterrole.out.yaml
  tools/rbac-gen/tests/duplicates.in.yaml
  tools/rbac-gen/tests/duplicates.out.yaml
  tools/rbac-gen/tests/simple.in.yaml
  tools/rbac-gen/tests/simple.out.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#59 NodeLocalDNS operator
  nodelocaldns/.gitignore
  nodelocaldns/Dockerfile
  nodelocaldns/Makefile
  nodelocaldns/PROJECT
  nodelocaldns/api/v1alpha1/groupversion_info.go
  nodelocaldns/api/v1alpha1/nodelocaldns_types.go
  nodelocaldns/api/v1alpha1/zz_generated.deepcopy.go
  nodelocaldns/channels/packages/nodelocaldns/1.15.0/manifest.yaml
  nodelocaldns/channels/stable
  nodelocaldns/config/certmanager/certificate.yaml
  nodelocaldns/config/certmanager/kustomization.yaml
  nodelocaldns/config/certmanager/kustomizeconfig.yaml
  nodelocaldns/config/crd/bases/addons.x-k8s.io_nodelocaldns.yaml
  nodelocaldns/config/crd/bases/app.k8s.io_application.yaml
  nodelocaldns/config/crd/kustomization.yaml
  nodelocaldns/config/crd/kustomizeconfig.yaml
  nodelocaldns/config/crd/patches/cainjection_in_nodelocaldns.yaml
  nodelocaldns/config/crd/patches/webhook_in_nodelocaldns.yaml
  nodelocaldns/config/default/kustomization.yaml
  nodelocaldns/config/default/manager_auth_proxy_patch.yaml
  nodelocaldns/config/default/manager_webhook_patch.yaml
  nodelocaldns/config/default/webhookcainjection_patch.yaml
  nodelocaldns/config/manager/kustomization.yaml
  nodelocaldns/config/manager/manager.yaml
  nodelocaldns/config/prometheus/kustomization.yaml
  nodelocaldns/config/prometheus/monitor.yaml
  nodelocaldns/config/rbac/auth_proxy_role.yaml
  nodelocaldns/config/rbac/auth_proxy_role_binding.yaml
  nodelocaldns/config/rbac/auth_proxy_service.yaml
  nodelocaldns/config/rbac/kustomization.yaml
  nodelocaldns/config/rbac/leader_election_role.yaml
  nodelocaldns/config/rbac/leader_election_role_binding.yaml
  nodelocaldns/config/rbac/localnodedns_editor_role.yaml
  nodelocaldns/config/rbac/localnodedns_viewer_role.yaml
  nodelocaldns/config/rbac/manager_role.yaml
  nodelocaldns/config/rbac/manager_role_binding.yaml
  nodelocaldns/config/rbac/role.yaml
  nodelocaldns/config/rbac/role_binding.yaml
  nodelocaldns/config/samples/addons_v1alpha1_localnodedns.yaml
  nodelocaldns/config/webhook/kustomization.yaml
  nodelocaldns/config/webhook/kustomizeconfig.yaml
  nodelocaldns/config/webhook/manifests.yaml
  nodelocaldns/config/webhook/service.yaml
  nodelocaldns/controllers/nodelocaldns_controller.go
  nodelocaldns/controllers/nodelocaldns_controller_test.go
  nodelocaldns/controllers/tests/simple.in.yaml
  nodelocaldns/controllers/tests/simple.out.yaml
  nodelocaldns/controllers/utils.go
  nodelocaldns/go.mod
  nodelocaldns/go.sum
  nodelocaldns/hack/boilerplate.go.txt
  nodelocaldns/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
