Repository kubernetes-sigs/cluster-addons, pull requests merged in 2020-03, with the labels that each got.

#45 Updates CoreDNS readme for kubebuilder 2.0
  coredns/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#48 Fix minor nit in kubebuilder command
  coredns/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#44 Operator for the Kubernetes dashboard
  dashboard/.gitignore
  dashboard/Dockerfile
  dashboard/Makefile
  dashboard/PROJECT
  dashboard/api/v1alpha1/dashboard_types.go
  dashboard/api/v1alpha1/groupversion_info.go
  dashboard/api/v1alpha1/zz_generated.deepcopy.go
  dashboard/channels/develop
  dashboard/channels/packages/dashboard/1.10.1/manifest.yaml
  dashboard/channels/packages/dashboard/1.8.3/manifest.yaml
  dashboard/channels/packages/dashboard/2.0.0/manifest.yaml
  dashboard/channels/stable
  dashboard/config/certmanager/certificate.yaml
  dashboard/config/certmanager/kustomization.yaml
  dashboard/config/certmanager/kustomizeconfig.yaml
  dashboard/config/crd/bases/addons.k8s.io_dashboards.yaml
  dashboard/config/crd/bases/app.k8s.io_application.yaml
  dashboard/config/crd/kustomization.yaml
  dashboard/config/crd/kustomizeconfig.yaml
  dashboard/config/crd/patches/cainjection_in_dashboards.yaml
  dashboard/config/crd/patches/webhook_in_dashboards.yaml
  dashboard/config/default/kustomization.yaml
  dashboard/config/default/manager_auth_proxy_patch.yaml
  dashboard/config/default/manager_webhook_patch.yaml
  dashboard/config/default/webhookcainjection_patch.yaml
  dashboard/config/manager/kustomization.yaml
  dashboard/config/manager/manager.yaml
  dashboard/config/prometheus/kustomization.yaml
  dashboard/config/prometheus/monitor.yaml
  dashboard/config/rbac/auth_proxy_role.yaml
  dashboard/config/rbac/auth_proxy_role_binding.yaml
  dashboard/config/rbac/auth_proxy_service.yaml
  dashboard/config/rbac/dashboard_editor_role.yaml
  dashboard/config/rbac/dashboard_viewer_role.yaml
  dashboard/config/rbac/kustomization.yaml
  dashboard/config/rbac/leader_election_role.yaml
  dashboard/config/rbac/leader_election_role_binding.yaml
  dashboard/config/rbac/role.yaml
  dashboard/config/rbac/role_binding.yaml
  dashboard/config/samples/addons_v1alpha1_dashboard.yaml
  dashboard/config/webhook/kustomization.yaml
  dashboard/config/webhook/kustomizeconfig.yaml
  dashboard/config/webhook/manifests.yaml
  dashboard/config/webhook/service.yaml
  dashboard/controllers/dashboard_controller.go
  dashboard/controllers/dashboard_controller_test.go
  dashboard/controllers/tests/patches-develop.in.yaml
  dashboard/controllers/tests/patches-develop.out.yaml
  dashboard/controllers/tests/patches-stable.in.yaml
  dashboard/controllers/tests/patches-stable.out.yaml
  dashboard/controllers/tests/simple-develop.in.yaml
  dashboard/controllers/tests/simple-develop.out.yaml
  dashboard/controllers/tests/simple-stable.in.yaml
  dashboard/controllers/tests/simple-stable.out.yaml
  dashboard/go.mod
  dashboard/go.sum
  dashboard/hack/boilerplate.go.txt
  dashboard/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#51 Add metrics-server-operator
  metrics-server/.gitignore
  metrics-server/Dockerfile
  metrics-server/Makefile
  metrics-server/PROJECT
  metrics-server/api/v1alpha1/groupversion_info.go
  metrics-server/api/v1alpha1/metricsserver_types.go
  metrics-server/api/v1alpha1/zz_generated.deepcopy.go
  metrics-server/channels/packages/metrics-server/0.3.6/manifest.yaml
  metrics-server/channels/stable
  metrics-server/config/certmanager/certificate.yaml
  metrics-server/config/certmanager/kustomization.yaml
  metrics-server/config/certmanager/kustomizeconfig.yaml
  metrics-server/config/crd/bases/addons.example.org_metricsservers.yaml
  metrics-server/config/crd/bases/addons.x-k8s.io_metricsservers.yaml
  metrics-server/config/crd/kustomization.yaml
  metrics-server/config/crd/kustomizeconfig.yaml
  metrics-server/config/crd/patches/cainjection_in_metricsservers.yaml
  metrics-server/config/crd/patches/webhook_in_metricsservers.yaml
  metrics-server/config/default/kustomization.yaml
  metrics-server/config/default/manager_auth_proxy_patch.yaml
  metrics-server/config/default/manager_webhook_patch.yaml
  metrics-server/config/default/webhookcainjection_patch.yaml
  metrics-server/config/manager/kustomization.yaml
  metrics-server/config/manager/manager.yaml
  metrics-server/config/prometheus/kustomization.yaml
  metrics-server/config/prometheus/monitor.yaml
  metrics-server/config/rbac/auth_proxy_role.yaml
  metrics-server/config/rbac/auth_proxy_role_binding.yaml
  metrics-server/config/rbac/auth_proxy_service.yaml
  metrics-server/config/rbac/kustomization.yaml
  metrics-server/config/rbac/leader_election_role.yaml
  metrics-server/config/rbac/leader_election_role_binding.yaml
  metrics-server/config/rbac/metricsserver_editor_role.yaml
  metrics-server/config/rbac/metricsserver_viewer_role.yaml
  metrics-server/config/rbac/role.yaml
  metrics-server/config/rbac/role_binding.yaml
  metrics-server/config/samples/addons_v1alpha1_metricsserver.yaml
  metrics-server/config/webhook/kustomization.yaml
  metrics-server/config/webhook/kustomizeconfig.yaml
  metrics-server/config/webhook/service.yaml
  metrics-server/controllers/metricsserver_controller.go
  metrics-server/controllers/metricsserver_controller_test.go
  metrics-server/controllers/tests/patches.in.yaml
  metrics-server/controllers/tests/patches.out.yaml
  metrics-server/go.mod
  metrics-server/go.sum
  metrics-server/hack/boilerplate.go.txt
  metrics-server/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
