Repository kubernetes-sigs/cluster-addons, pull requests merged in 2020-07, with the labels that each got.

#35 kubeproxy operator
  kubeproxy/.gitignore
  kubeproxy/Dockerfile
  kubeproxy/Makefile
  kubeproxy/PROJECT
  kubeproxy/README.md
  kubeproxy/api/v1alpha1/groupversion_info.go
  kubeproxy/api/v1alpha1/kubeproxy_types.go
  kubeproxy/api/v1alpha1/zz_generated.deepcopy.go
  kubeproxy/channels/packages/kubeproxy/1.15.0/manifest.yaml
  kubeproxy/channels/stable
  kubeproxy/config/certmanager/certificate.yaml
  kubeproxy/config/certmanager/kustomization.yaml
  kubeproxy/config/certmanager/kustomizeconfig.yaml
  kubeproxy/config/crd/bases/addons.x-k8s.io_kubeproxies.yaml
  kubeproxy/config/crd/bases/app.k8s.io_application.yaml
  kubeproxy/config/crd/kustomization.yaml
  kubeproxy/config/crd/kustomizeconfig.yaml
  kubeproxy/config/crd/patches/cainjection_in_kubeproxies.yaml
  kubeproxy/config/crd/patches/webhook_in_kubeproxies.yaml
  kubeproxy/config/default/kustomization.yaml
  kubeproxy/config/default/manager_auth_proxy_patch.yaml
  kubeproxy/config/default/manager_prometheus_metrics_patch.yaml
  kubeproxy/config/default/manager_webhook_patch.yaml
  kubeproxy/config/default/webhookcainjection_patch.yaml
  kubeproxy/config/manager/kustomization.yaml
  kubeproxy/config/manager/manager.yaml
  kubeproxy/config/manager/patches/apiserver_endpoint.patch.yaml
  kubeproxy/config/manager/patches/tolerations_controlplane.patch.yaml
  kubeproxy/config/manager/role.yaml
  kubeproxy/config/rbac/auth_proxy_role.yaml
  kubeproxy/config/rbac/auth_proxy_role_binding.yaml
  kubeproxy/config/rbac/auth_proxy_service.yaml
  kubeproxy/config/rbac/kustomization.yaml
  kubeproxy/config/rbac/leader_election_role.yaml
  kubeproxy/config/rbac/leader_election_role_binding.yaml
  kubeproxy/config/rbac/role.yaml
  kubeproxy/config/rbac/role_binding.yaml
  kubeproxy/config/samples/addons_v1alpha1_kubeproxy.yaml
  kubeproxy/config/webhook/kustomization.yaml
  kubeproxy/config/webhook/kustomizeconfig.yaml
  kubeproxy/config/webhook/manifests.yaml
  kubeproxy/config/webhook/service.yaml
  kubeproxy/controllers/kubeproxy_controller.go
  kubeproxy/controllers/kubeproxy_controller_test.go
  kubeproxy/controllers/tests/simple-stable.in.yaml
  kubeproxy/controllers/tests/simple-stable.out.yaml
  kubeproxy/create-cluster.sh
  kubeproxy/go.mod
  kubeproxy/go.sum
  kubeproxy/hack/boilerplate.go.txt
  kubeproxy/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#55 Update kubebuilder annotations for dashboard
  dashboard/Dockerfile
  dashboard/Makefile
  dashboard/config/manager/kustomization.yaml
  dashboard/config/rbac/role.yaml
  dashboard/controllers/dashboard_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#54 Update kubebuilder annotations for metrics-server
  metrics-server/Dockerfile
  metrics-server/Makefile
  metrics-server/config/crd/bases/addons.x-k8s.io_metricsservers.yaml
  metrics-server/config/manager/kustomization.yaml
  metrics-server/config/rbac/role.yaml
  metrics-server/controllers/metricsserver_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#58 Adding documentation for CoreDNS operator and building an addon-operator
  README.md
  coredns/README.md
  walkthrough.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#70 Adds role for manager
  kubeproxy/config/manager/patches/apiserver_endpoint.patch.yaml
  kubeproxy/config/rbac/kustomization.yaml
  kubeproxy/config/rbac/manager_role.yaml
  kubeproxy/config/rbac/manager_rolebinding.yaml
  kubeproxy/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#71 Uses packages from declarative pattern repo
  nodelocaldns/api/v1alpha1/nodelocaldns_types.go
  nodelocaldns/controllers/nodelocaldns_controller.go
  nodelocaldns/go.mod
  nodelocaldns/go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#63 Move the framework for smoketests to a new test dir
  .gitignore
  coredns/go.mod
  dashboard/Makefile
  go.mod
  go.sum
  metrics-server/Makefile
  test/boilerplate.go.txt
  test/smoketest.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#74 Update the stable CoreDNS version to v1.7.0
  coredns/channels/packages/coredns/1.7.0/Corefile
  coredns/channels/packages/coredns/1.7.0/clusterrole.yaml
  coredns/channels/packages/coredns/1.7.0/clusterrolebinding.yaml
  coredns/channels/packages/coredns/1.7.0/deployment.yaml
  coredns/channels/packages/coredns/1.7.0/kustomization.yaml
  coredns/channels/packages/coredns/1.7.0/service.yaml
  coredns/channels/packages/coredns/1.7.0/serviceaccount.yaml
  coredns/channels/stable
  coredns/config/samples/addons_v1alpha1_coredns.yaml
  coredns/controllers/tests/patches-stable.in.yaml
  coredns/controllers/tests/patches-stable.out.yaml
  coredns/controllers/tests/simple-stable.out.yaml
  coredns/go.mod
  coredns/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#73 Kubectl plugin for resources that have a particular ownerref
  tools/kubectl-ownerref/go.mod
  tools/kubectl-ownerref/go.sum
  tools/kubectl-ownerref/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL
