Repository kubernetes-sigs/cluster-addons, pull requests merged in 2020-09, with the labels that each got.

#79 First steps towards a staging cloudbuild
  dev/staging/cloudbuild.yaml
  dev/staging/push.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#77 Adds status subresource in crd
  tools/generic-addon/go.mod
  tools/generic-addon/go.sum
  tools/generic-addon/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#80 Puts status subresource in all operators
  coredns/api/v1alpha1/coredns_types.go
  coredns/config/crd/bases/addons.x-k8s.io_coredns.yaml
  coredns/config/webhook/manifests.yaml
  dashboard/api/v1alpha1/dashboard_types.go
  dashboard/config/crd/bases/addons.x-k8s.io_dashboards.yaml
  flannel/api/v1alpha1/flannel_types.go
  flannel/config/crd/bases/addons.x-k8s.io_flannels.yaml
  generic/api/v1alpha1/generic_types.go
  generic/config/crd/bases/addons.x-k8s.io_generics.yaml
  kubeproxy/api/v1alpha1/kubeproxy_types.go
  kubeproxy/config/crd/bases/addons.x-k8s.io_kubeproxies.yaml
  metrics-server/api/v1alpha1/metricsserver_types.go
  metrics-server/config/crd/bases/addons.x-k8s.io_metricsservers.yaml
  nodelocaldns/api/v1alpha1/nodelocaldns_types.go
  nodelocaldns/config/crd/bases/addons.x-k8s.io_nodelocaldns.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#72 Add new operators to test
  coredns/config/crd/bases/addons.x-k8s.io_coredns.yaml
  flannel/config/crd/bases/addons.x-k8s.io_flannels.yaml
  hack/unit-test.sh
  kubeproxy/Makefile
  kubeproxy/config/crd/bases/addons.x-k8s.io_kubeproxies.yaml
  metrics-server/config/crd/bases/addons.x-k8s.io_metricsservers.yaml
  nodelocaldns/config/crd/bases/addons.x-k8s.io_nodelocaldns.yaml
  nodelocaldns/controllers/nodelocaldns_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#78 Centralize Documentations and README.md
  README.md
  dashboard/README.md
  docs/create-operator.md
  tools/kubectl-ownerref/README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#82 staging build: fix up build tagging
  bootstrap/Makefile
  dev/staging/cloudbuild.yaml
  dev/staging/push.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#86 Fix failing go mod test
  tools/generic-addon/go.mod
  tools/generic-addon/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S
