Repository kubernetes-sigs/cluster-addons, pull requests merged in 2021-11, with the labels that each got.

#108 Update coredns versions to latest
  coredns/README.md
  coredns/channels/packages/coredns/1.7.0/Corefile
  coredns/channels/packages/coredns/1.7.0/deployment.yaml
  coredns/channels/packages/coredns/1.8.0/Corefile
  coredns/channels/packages/coredns/1.8.0/clusterrole.yaml
  coredns/channels/packages/coredns/1.8.0/clusterrolebinding.yaml
  coredns/channels/packages/coredns/1.8.0/deployment.yaml
  coredns/channels/packages/coredns/1.8.0/kustomization.yaml
  coredns/channels/packages/coredns/1.8.0/service.yaml
  coredns/channels/packages/coredns/1.8.0/serviceaccount.yaml
  coredns/channels/packages/coredns/1.8.4/Corefile
  coredns/channels/packages/coredns/1.8.4/clusterrole.yaml
  coredns/channels/packages/coredns/1.8.4/clusterrolebinding.yaml
  coredns/channels/packages/coredns/1.8.4/deployment.yaml
  coredns/channels/packages/coredns/1.8.4/kustomization.yaml
  coredns/channels/packages/coredns/1.8.4/service.yaml
  coredns/channels/packages/coredns/1.8.4/serviceaccount.yaml
  coredns/channels/stable
  coredns/config/samples/addons_v1alpha1_coredns.yaml
  coredns/controllers/tests/patches-stable.out.yaml
  coredns/controllers/tests/simple-stable.out.yaml
  coredns/go.mod
  coredns/go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm

#105 Update README in kubeproxy-operator
  kubeproxy/README.md
Labels: cncf-cla: yes, approved, size/XS, lgtm

#102 kubectl-ownerref: use kubectl helpers
  tools/kubectl-ownerref/go.mod
  tools/kubectl-ownerref/go.sum
  tools/kubectl-ownerref/main.go
Labels: cncf-cla: yes, size/XXL, approved, lgtm
