Repository kubernetes-sigs/cluster-addons, pull requests merged in 2022-03, with the labels that each got.

#113 Fix dead links on README
  README.md
Labels: cncf-cla: yes, approved, size/XS, lgtm

#110 rbac-generator improvements
  tools/rbac-gen/main.go
  tools/rbac-gen/pkg/convert/convert.go
  tools/rbac-gen/pkg/convert/convert_test.go
  tools/rbac-gen/pkg/convert/kubebuilder.go
  tools/rbac-gen/pkg/convert/ruleset.go
  tools/rbac-gen/pkg/convert/tests/clusterrole.out.kubebuilder
  tools/rbac-gen/pkg/convert/tests/clusterrole.out.yaml
  tools/rbac-gen/pkg/convert/tests/duplicates.out.kubebuilder
  tools/rbac-gen/pkg/convert/tests/duplicates.out.yaml
  tools/rbac-gen/pkg/convert/tests/simple.out.kubebuilder
  tools/rbac-gen/pkg/convert/tests/simple.out.yaml
  tools/rbac-gen/pkg/convert/yaml.go
Labels: cncf-cla: yes, size/XL, approved, lgtm

#115 Update makefiles for go-get changes
  coredns/Makefile
  dashboard/Makefile
  dashboard/config/crd/bases/addons.x-k8s.io_dashboards.yaml
  flannel/Makefile
  kubeproxy/Makefile
  metrics-server/Makefile
  nodelocaldns/Makefile
  tools/rbac-gen/pkg/convert/convert_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#116 Update readme with some small tweaks
  README.md
Labels: cncf-cla: yes, approved, size/XS, lgtm
